#pragma config(Motor,  port2,           topLeft,       tmotorVex393, openLoop)
#pragma config(Motor,  port3,           backLeft,      tmotorVex393, openLoop)
#pragma config(Motor,  port4,           topRight,      tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port5,           backRight,     tmotorVex393, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void leftSide(int power) {
	motor[topLeft] = power;

}

task main()
{
	int joy_right;
	int joy_left;
	int breaker = 1;
	int threshold = 10

	while(breaker == 1) {
		joy_right = (vexRT[Ch2]);
		joy_left = (vexRT[Ch3]);

		motor[topLeft] = joy_left;
		motor[backLeft] = joy_left;
		motor[topRight] = joy_right;
		motor[backRight] = joy_right;
	}
}
