#pragma config(Motor,  port2,           topLeft,       tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port3,           backLeft,      tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port4,           topRight,      tmotorVex393, openLoop)
#pragma config(Motor,  port5,           backRight,     tmotorVex393, openLoop)
#pragma config(Motor,  port6,           liftLeftTop,   tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port7,           liftLeftBack,  tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port8,           liftRightTop,  tmotorVex393, openLoop)
#pragma config(Motor,  port9,           liftRightBack, tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//void leftSide(int power) {
//	motor[topLeft] = power;
//
//}

task main()
{
	int joy_right;
	int joy_left;
	int mode = 1;
//	int threshold = 10;
	while(true) {
		if(vexRT[Btn7D] != 1) {
			joy_right = (vexRT[Ch2]) / mode;
			joy_left = (vexRT[Ch3]) / mode;

			if(vexRT[Btn6U] == 1) {
				motor[liftLeftBack] = 127;
				motor[liftLeftTop] = 127;
				motor[liftRightTop] = 127;
				motor[liftRightBack] = 127;

				motor[topLeft] = joy_left;
				motor[backLeft] = joy_left;
				motor[topRight] = joy_right;
				motor[backRight] = joy_right;
			}

			else if(vexRT[Btn6D] == 1) {
				motor[liftLeftBack] = -127;
				motor[liftLeftTop] = -127;
				motor[liftRightTop] = -127;
				motor[liftRightBack] = -127;

				motor[topLeft] = joy_left;
				motor[backLeft] = joy_left;
				motor[topRight] = joy_right;
				motor[backRight] = joy_right;
			}
			else {
				motor[liftLeftBack] = 0;
				motor[liftLeftTop] = 0;
				motor[liftRightTop] = 0;
				motor[liftRightBack] = 0;
			}

			motor[topLeft] = joy_left;
			motor[backLeft] = joy_left;
			motor[topRight] = joy_right;
			motor[backRight] = joy_right;
			wait1Msec(10);
		}
		else if(vexRT[Btn7D] == 1) {
			if(mode == 1) {
				mode = 3;
			}
			else if(mode == 3) {
				mode = 1;
			}
		}
	}
}
