#pragma config(Motor,  port2,           topLeft,       tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port3,           backLeft,      tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port4,           topRight,      tmotorVex393, openLoop)
#pragma config(Motor,  port5,           backRight,     tmotorVex393, openLoop)
#pragma config(Motor,  port6,           liftLeftTop,   tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port7,           liftLeftBack,  tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port8,           liftRightTop,  tmotorVex393, openLoop)
#pragma config(Motor,  port9,           liftRightBack, tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/**
 * Function to drive the drive train
 * @param power int power to be suppplied to the drive train
 *              postive = forward
 *              negative = backwards
 */
void drive(int power) {
	motor[topLeft] = power;
	motor[topRight] = power;
	motor[backLeft] = power;
	motor[backRight] = power;
}

/**
 * Function to drive the left side of the drive train
 * @param power int power to be supplied to the left side of the drive train
 *              postive = forward
 *              negative = backwards
 */
void driveLeft(int power) {
	motor[topLeft] = power;
	motor[backLeft] = power;
}

/**
 * Function to drive the right side of the drive train
 * @param power int power to be supplied to right side fo the drive train
 *              postive = forward
 *              negative = backwards
 */
void driveRight(int power) {
	motor[topRight] = power;
	motor[backRight] = power;
}

/**
 * Function to control the lift
 * @param power int power to be supplied to the lift motors
 *              postive = upwards
 *              negative = downwards
 */
void lift(int power) {
	motor[liftLeftBack] = power;
	motor[liftLeftTop] = power;
	motor[liftRightTop] = power;
	motor[liftRightBack] = power;
}

/**
 * Function to change the speed of the drive (lower speed means greater accuarcy)
 * @param currentMode int current mode of the drive, return the mode that the current mode isn't
 */
int changeMode(int currentMode) {
	int newMode;
	if(currentMode == 1) {
		newMode = 2;
	}
	else if(currentMode == 2) {
		newMode = 1;
	}
	return newMode;
}

task main()
{
	/**
	 * Right joystick
	 */
	int joy_right;

	/**
	 * Left joystick
	 */
	int joy_left;

	/**
	 * Drive mode (1 for normal, 2 for accuarcy)
	 */
	int mode = 1;

	/**
	 * Never ending while loop for constant refreshing of code
	 */
	while(true) {
		/**
		 * If btn7D ISN'T pressed
		 */
		if(vexRT[Btn7D] != 1) {
			/**
			 * Both right and left joystick are the raw channel values divided by the mode
			 * So, if the mode is 1, they will be at full speed, but if the mode is at 2,
			 * they will be at half speed
			 */
			joy_right = (vexRT[Ch2]) / mode;
			joy_left = (vexRT[Ch3]) / mode;

			/**
			 * If btn6U is pressed
			 */
			if(vexRT[Btn6U] == 1) {
				/**
				 * Brint the lift upwards at full speed
				 */
				lift(127);

				/**
				 * Left drive is the left joystick
				 * Right drive is the right joystick
				 */
				driveLeft(joy_left);
				driveRight(joy_right);
			}

			/**
			 * If btn6D is pressed
			 */
			else if(vexRT[Btn6D] == 1) {
				/**
				 * Lower the lift at full power
				 */
				lift(-127);

				/**
				 * Left drive is the left joystick
				 * Right drive is the right joysitck
				 */
				driveLeft(joy_left);
				driveRight(joy_right);
			}
			/**
			 * If no button is pressed
			 */
			else {
				/**
				 * No power is supplied to the lift
				 */
				lift(0);
			}

			/**
			 * Left drive is the left joystick
			 * RIght drive is the right joystick
			 */
			driveLeft(joy_left);
			driveRight(joy_right);

			/**
			 * Wait 10 milliseconds for code refresh
			 */
			wait1Msec(10);
		}

		/**
		 * If btn7D is pressed
		 */
		else if(vexRT[Btn7D] == 1) {
			/**
			 * Mode (global variable) is equal to the returned value of the
			 * function change mode
			 */
			mode = changeMode(mode);
		}
	}
}
