#pragma config(Motor,  port2,           topLeft,       tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port3,           backLeft,      tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port4,           topRight,      tmotorVex393, openLoop)
#pragma config(Motor,  port5,           backRight,     tmotorVex393, openLoop)
#pragma config(Motor,  port6,           liftLeftTop,   tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port7,           liftLeftBack,  tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port8,           liftRightTop,  tmotorVex393, openLoop)
#pragma config(Motor,  port9,           liftRightBack, tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void drive(int power) {
	motor[topLeft] = power;
	motor[topRight] = power;
	motor[backLeft] = power;
	motor[backRight] = power;
}

void driveLeft(int power) {
	motor[topLeft] = power;
	motor[backLeft] = power;
}


void driveRight(int power) {
	motor[topRight] = power;
	motor[backRight] = power;
}


void lift(int power) {
	motor[liftLeftBack] = power;
	motor[liftLeftTop] = power;
	motor[liftRightTop] = power;
	motor[liftRightBack] = power;
}

float changeMode(float currentMode) {
	float newMode;
	if(currentMode == .9) {
		newMode =  .3;
	}
	else if(currentMode == .3) {
		newMode =  .9;
	}
	return newMode;
}

task main()
{
	int joy_right;
	int joy_left;
	float mode = 0.9;

	while(true) {

		joy_right = (vexRT[Ch2]) * mode;
		joy_left = (vexRT[Ch3]) * mode;

		if(vexRT[Btn6U] == 1) {
			lift(127);

			driveLeft(joy_left);
			driveRight(joy_right);
		}

		else if(vexRT[Btn6D] == 1) {
			lift(-127);

			driveLeft(joy_left);
			driveRight(joy_right);
		}
		else {

			lift(0);
		}

		if (vexRT[Btn7D] == 1) {
			mode = changeMode(mode);
		}

		driveLeft(joy_left);
		driveRight(joy_right);

		wait1Msec(10);
	}
}
