#pragma config(Sensor, in8,    gyro,           sensorGyro)
#pragma config(Motor,  port2,           driveRight,    tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port3,           driveLeft,     tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
  SensorType[gyro] = sensorNone;
  wait1Msec(1000);
  SensorType[gyro] = sensorGyro;
  wait1Msec(2000);

  SensorScale[gyro] = 190;
  SensorFullCount[gyro] = 3600;

	while(true) {
		writeDebugStreamLine("Gyro Value: %3.2f\n", SensorValue[gyro]);
		wait1Msec(50);
	}
}
